build_task1: 
	g++ -std=c++11  ./Task1/task1.cpp  -w -o ./Task1/task1  -L/usr/X11/lib -I /usr/local/include/X11 -I /usr/X11/include -L/opt/homebrew/opt/jpeg/lib -I/opt/homebrew/opt/jpeg/include -ljpeg -lX11

run_task1: build_task1
	./Task1/task1 "/Users/minaashraf/university/fall_2022/GPU/GPU_programming_with_CUDA/assignment 3/Task1/lena.jpeg"


build_task2:
	g++ -std=c++11  ./Task2/task2.cpp  -w -o ./Task2/task2  -L/usr/X11/lib -I /usr/local/include/X11 -I /usr/X11/include -L/opt/homebrew/opt/jpeg/lib -I/opt/homebrew/opt/jpeg/include -ljpeg -lX11

run_task2: build_task2
	./Task2/task2 "/Users/minaashraf/university/fall_2022/GPU/GPU_programming_with_CUDA/assignment 3/Task1/lena.jpeg"


